### ISSUE TITLE
Readme Typo?

### ISSUE THREAD

**Issue by KevinDanikowski** [slorber/use-async-setState#4]
In the readme examples it reads `await setStateAsync({...state: counter: state.counter + 1});`, should it not be a comma after state, so it reads like `await setStateAsync({...state, counter: state.counter + 1});`?

I'm not sure if this is a typescript thing, as i code in JS mainly, but this was tripping me up. If this is correct, some elaboration would be appreciated for my own insight :) thanks @slorber  , I appreciate it, this hook helped significantly with my current project.

**Comment by slorber** [comment]
thanks, it was a typo ;)

nice to know this hook was useful ;)
